version: "3.8"
services:
  vsftpdserver:
    build: .
    privileged: true
    image: "vsftpd-image"
    container_name: "vsftpd-server"
    ports:
      - "80:80"
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 40000-40020:40000-40020
    volumes:
      - ${docker_code}:/install
      # - ${etcdir}:/tmp/etc:ro
      # - /sys/kernel/debug:/sys/kernel/debug:rw
      # - /lib/modules:/lib/modules:ro
      # - /usr/src:/usr/src:ro
      # - /etc/localtime:/etc/localtime:ro
    command: /install/vsftpd/run.sh

    tty: true
    stdin_open: true