version: "3.3"
services:
  postgres:
    build: .
    privileged: true
    image: "postgres-image"
    container_name: "postgres-server"
    environment:
      POSTGRES_USER: postgres
    ports:
        - "5432:5432"
    volumes:
      - ${docker_code}:/install
      # - /sys/kernel/debug:/sys/kernel/debug:rw
      # - /lib/modules:/lib/modules:ro
      # - /usr/src:/usr/src:ro
      # - /etc/localtime:/etc/localtime:ro
    command: /install/postgres/run.sh

    tty: true
    stdin_open: true